title: The Digital Polis
tagline: Solipsist Nation
description: A blog about innovation, geekery, and the obsessions of a maker
url: http://ecafe.org
#url: http://localhost:4000

disqus_shortname: digitalpolis

owner:
  name:             Mark Cheverton
  avatar:           avatar.jpg
  bio:              "Geek, maker, artist, and entrepreuneur. CTO at Redgate software."
  email:            mark.cheverton@ecafe.org
  twitter:          ennui2342
  github:           ennui2342
  stackexchange:    ennui2342
  linkedin:         markcheverton
  instagram:        
  flickr:           ennui2342
  # For Google Authorship https://plus.google.com/authorship
  google_plus:      https://plus.google.com/110560929370891202956

#google_analytics:   UA-220560-6
google_verify:      P7biiNYjgRQdJzNWdE3-TT0jB4j7wbw7HKYvrWe6JMc
# # https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# # Links to include in top navigation
# # For external links add external: true
links:
  - title: About
    url: /
  - title: Blog
    url: /blog
#  - title: External Link
#    url: http://mademistakes.com
#    external: true

timezone:    Europe/London
future:      true
pygments:    true
markdown:    redcarpet

default_feature: feature-watercolour.jpg

exclude: ['node_modules', '*.scriv/*']

